# Generated by Django 4.1.4 on 2023-02-17 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomIndustryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomInterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_area_name', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(blank=True, max_length=500)),
                ('add_tax', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('price', models.CharField(blank=True, max_length=150)),
                ('about', models.CharField(blank=True, max_length=100000)),
                ('overview', models.CharField(blank=True, max_length=100000)),
                ('how_it_work', models.CharField(blank=True, max_length=100000)),
                ('execution_time', models.CharField(blank=True, max_length=100000)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('image1', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image1')),
                ('image2', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image2')),
                ('image3', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image3')),
                ('image4', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image4')),
                ('image5', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image5')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customcategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customsubcategory')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customtax')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('', 'Choose gender'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('avatar', models.ImageField(default='profile/image/default.gif', upload_to=users.models.user_directory_path)),
                ('dob', models.CharField(blank=True, help_text='Pattern = dd-mm-yyyy', max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        # migrations.AddField(
        #     model_name='CustomSolution',
        #     name='short_description',
        #     field=models.CharField(blank=True, max_length=100000),
        # ),
    ]
