# Generated by Django 4.1.4 on 2023-03-02 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_city_customuser_pincode_customuser_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_name', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('audience_preference', models.BooleanField(default=False)),
                ('age_range', models.CharField(blank=True, max_length=1000, null=True)),
                ('occupation', models.CharField(blank=True, max_length=1000, null=True)),
                ('income_range', models.CharField(blank=True, max_length=1000, null=True)),
                ('car_price_range', models.CharField(blank=True, max_length=1000, null=True)),
                ('interest_area', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_responses', models.IntegerField(default=0)),
                ('solution_price', models.FloatField(default=0.0)),
                ('subtotal', models.FloatField(default=0.0)),
                ('tax_per', models.IntegerField(default=0)),
                ('total_tax', models.FloatField(default=0.0)),
                ('final_total', models.FloatField(default=0.0)),
                ('order_status', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customcategory')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customsolution')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customsubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('store_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('store_city', models.CharField(blank=True, max_length=1000, null=True)),
                ('store_state', models.CharField(blank=True, max_length=1000, null=True)),
                ('store_postalcode', models.IntegerField(default=0)),
                ('store_responses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_store_data', to='users.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_price', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='order_product_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_project_data', to='users.orders')),
            ],
        ),
    ]
