# Generated by Django 4.1.4 on 2023-03-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_orders_orderstoredata_orderprojectdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsolution',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
