# Generated by Django 4.1.4 on 2023-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customsolution_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='industry_selection',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
