# Generated by Django 4.1.4 on 2023-03-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_orders_industry_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_product_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderprojectdata',
            name='image',
        ),
        migrations.AlterField(
            model_name='orderprojectdata',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderprojectdata',
            name='images',
            field=models.ManyToManyField(to='users.orderproductimages'),
        ),
    ]
