# Generated by Django 4.1.4 on 2023-03-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customsolution_url_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprojectdata',
            name='product_price',
        ),
        migrations.AddField(
            model_name='orderprojectdata',
            name='product_brand',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orderprojectdata',
            name='product_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
