# Generated by Django 4.1.4 on 2023-03-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_orderprojectdata_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprojectdata',
            name='images',
        ),
    ]
