# Generated by Django 4.1.4 on 2023-03-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_orderprojectdata_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.orderprojectdata'),
        ),
    ]
