# Generated by Django 4.1.4 on 2023-03-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_orderproductimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.orderprojectdata'),
        ),
    ]
