# Generated by Django 4.1.4 on 2023-03-18 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_orderproductimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprojectdata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='orderproductimages',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderproductimages',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='order_product_images/'),
        ),
        migrations.AlterField(
            model_name='orderproductimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_project_id', to='users.orderprojectdata'),
        ),
    ]
