# Generated by Django 4.1.4 on 2023-03-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_orderprojectdata_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductimages',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproductimages',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_data', to='users.orders'),
        ),
    ]
