# Generated by Django 4.1.4 on 2023-03-22 06:54

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='profile/image/default.gif', upload_to=users.models.user_directory_path),
        ),
    ]
