# Generated by Django 4.1.4 on 2023-04-21 13:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_draftsendmail_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsendmail',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='profile/image/default.gif', upload_to=users.models.user_directory_path),
        ),
    ]
