# Generated by Django 4.1.4 on 2023-05-02 13:39

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_customuser_type_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='profile/image/default.gif', upload_to=users.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, default='user', max_length=150),
        ),
    ]
